wutsi:
  application:
    server-url: https://wutsi-gateway-prod.herokuapp.com/login  # in PROD, use the API gateway
  platform:
    security:
      api-key: ${API_KEY}
    cache:
      type: memcached
      memcached:
        username: ${MEMCACHIER_USERNAME}
        password: ${MEMCACHIER_PASSWORD}
        servers: ${MEMCACHIER_SERVERS}
        ttl: 86400
