wutsi:
  application:
    server-url: https://wutsi-gateway-prod.herokuapp.com/login  # in PROD, use the API gateway
  toggles:
    send-sms-code: true
    verification: true
  platform:
    cache:
      type: memcached
      memcached:
        username: ${MEMCACHIER_USERNAME}
        password: ${MEMCACHIER_PASSWORD}
        servers: ${MEMCACHIER_SERVERS}
        ttl: 86400
    messaging:
      sms:
        type: aws
        aws:
          region: us-east-1
    security:
      api-key: ${API_KEY}
    stream:
      type: rabbitmq
      rabbitmq:
        url: ${CLOUDAMQP_URL}
